import {
    Button,
    StandardTableView,
    TextEdit,
    LineEdit,
    TabWidget,
    HorizontalBox,
    VerticalBox
} from "std-widgets.slint";

component ScanResults inherits Rectangle {
    // StandardTableView rows are a model of models (a list of rows, where each row is a list of items)
    in-out property <[[StandardListViewItem]]> device_rows: [];
    in-out property <int> current-row: tv.current-row;
    callback sort-scan-results-cb(int, bool);

    min-width: 500px;
    min-height: 200px;
    VerticalLayout {
        tv := StandardTableView {
            sort-ascending(idx) => { sort-scan-results-cb(idx, true); }
            sort-descending(idx) => { sort-scan-results-cb(idx, false); }

            columns: [
                { title: "Address", min-width: 50px },
                { title: "RSSI" },
                { title: "Name" },
                { title: "Data" },
            ];
            rows: root.device_rows;
        }
    }
}

struct DeviceData {
    address: string,
    conn: int,
    text: string,               // this will be a GATT view later
}

component DeviceView inherits Rectangle {
    in property <DeviceData> data;
    background: #333;
    border-width: 1px;
    border-color: gray;

    Text {
        text: "View: " + root.data.address + " | Value: " + root.data.text;
        color: white;
    }
}

export enum Command { start-scan, stop-scan, connect, bond, disconnect }

export struct ScanFilter {
    text: string,
    column: int,
    ascending: bool,
}

export component AppWindow inherits Window {
    // Define the callback here so Rust can "see" it
    callback button(Command);

    in-out property <[[StandardListViewItem]]> scan_results_storage;
    in-out property <[[StandardListViewItem]]> scan_results <=> results.device_rows;
    in-out property <int> selected_device <=> results.current-row;
    in-out property <[DeviceData]> all-devices: [];
    in-out property <int> active-tab: 0;
    in-out property <ScanFilter> scan-filter: {text: "", column: 1, ascending: false};

    callback filter-scan-results(ScanFilter);

    VerticalLayout {
        HorizontalLayout {
            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;
                max-width: 100px;
                Button {
                    text: "Start scan";
                    clicked => {root.button(Command.start-scan);}
                }

                Button {
                    text: "Stop scan";
                    clicked => {root.button(Command.stop-scan);}
                }

                Button {
                    text: "Connect";
                    clicked => {root.button(Command.connect);}
                }

                Button {
                    text: "Bond";
                    clicked => {root.button(Command.bond);}
                }

                Button {
                    text: "Disconnect";
                    clicked => {root.button(Command.disconnect);}
                }
            }

            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                property<bool> scan-focused: true;

                VerticalBox {
                    padding: 0px;
                    HorizontalBox {
                        padding: 0px;
                        Button {
                            text: "Scan results";
                            clicked => { scan-focused = true; }
                        }

                        for device[i] in root.all-devices : Button {
                            text: device.address;
                            clicked => { root.active-tab = i+1; scan-focused = false; }
                        }
                    }

                    Rectangle {
                        min-height: 300px;
                        min-width: 600px;

                        VerticalBox {
                            visible: scan-focused;

                            LineEdit {
                                placeholder-text: "Device filter (name/address)";
                                edited(text) => {
                                    root.scan-filter.text = text;
                                    root.filter-scan-results(scan-filter);
                                }
                            }

                            Rectangle {
                                results := ScanResults {
                                    sort-scan-results-cb(idx, asc) => {
                                        root.scan-filter.column = idx;
                                        root.scan-filter.ascending = asc;
                                        root.filter-scan-results(scan-filter);
                                    }
                                }
                            }
                        }

                        for device[i] in root.all-devices : DeviceView {
                            data: device;
                            visible: (root.active-tab == i+1) && !scan-focused;
                        }
                    }
                }

                TextEdit {
                    min-height: 100px;
                    font-size: 12px;
                    text: "this is a log line\n and another";
                }
            }
        }
    }
}
