import {
    Button,
    StandardTableView,
    TextEdit,
    LineEdit,
    TabWidget,
    HorizontalBox,
    VerticalBox
} from "std-widgets.slint";

component ScanResults inherits Rectangle {
    // StandardTableView rows are a model of models (a list of rows, where each row is a list of items)
    in-out property <[[StandardListViewItem]]> device_rows: [];
    in-out property <int> current-row: tv.current-row;
    callback sort-scan-results-cb(int, bool);

    min-width: 500px;
    min-height: 200px;
    VerticalLayout {
        tv := StandardTableView {
            sort-ascending(idx) => { sort-scan-results-cb(idx, true); }
            sort-descending(idx) => { sort-scan-results-cb(idx, false); }

            columns: [
                { title: "Address", min-width: 50px },
                { title: "RSSI" },
                { title: "Name" },
                { title: "Data" },
            ];
            rows: root.device_rows;
        }
    }
}

struct DeviceData {
    address: string,
    conn: int,
    gatt: [[StandardListViewItem]],
}

component GattView inherits Rectangle {
    in property <DeviceData> data;
    in-out property <int> current-row: tv.current-row;

    min-width: 500px;
    min-height: 200px;
    VerticalLayout {
        tv := StandardTableView {
            columns: [
                { title: "Handle" },
                { title: "Type" },
                { title: "UUID" },
                { title: "Value" },
            ];
            rows: root.data.gatt;
        }
    }
}

export struct ScanFilter {
    text: string,
    column: int,
    ascending: bool,
}

export enum Command {
    start-scan,
    stop-scan,
    clear-scan,
    connect,
    disconnect,
    conn-param-update,
    att-mtu,
    bond,
    delete-bonds,
    stash-bonds,
    unstash-bonds,
    att-read,
    att-write-cmd,
    att-write-req,
    att-read-own,
    att-write-own,
    att-notify
}

struct MenuItemDesc {
    title: string,
    id: Command,
}

struct LazyMenuItem {
    title: string,
    items: [MenuItemDesc],
}

export component AppWindow inherits Window {
    // Define the callback here so Rust can "see" it
    callback button(Command);

    in-out property <string> log-text: "";
    public function log-go-to-bottom() {
        log-viewer.go-to-bottom();
    }
    in-out property <[[StandardListViewItem]]> scan_results_storage;
    in-out property <[[StandardListViewItem]]> scan_results <=> results.device_rows;
    in-out property <int> selected_device <=> results.current-row;
    in-out property <[DeviceData]> all-devices: [];
    in-out property <int> active-tab: 0;
    in-out property <ScanFilter> scan-filter: {text: "", column: 1, ascending: false};

    callback filter-scan-results(ScanFilter);
    property <[LazyMenuItem]> menus : [
        {
            title: "Connection",
            items: [
                {title: "Start scan", id: Command.start-scan},
                {title: "Stop scan", id: Command.stop-scan},
                {title: "Clear scan results", id: Command.clear-scan},
                {title: "Connect", id: Command.connect},
                {title: "Disconnect", id: Command.disconnect},
                {title: "Update conn params", id: Command.conn-param-update},
            ],
        },
        {
            title: "Security",
            items: [
                {title: "Bond / re-encrypt", id: Command.bond},
                {title: "Stash bonds", id: Command.stash-bonds},
                {title: "Unstash bonds", id: Command.unstash-bonds},
                {title: "Delete bonds", id: Command.delete-bonds},
            ],
        },
        {
            title: "GATT Client",
            items: [
                {title: "Read", id: Command.att-read},
                {title: "Write (command)", id: Command.att-write-cmd},
                {title: "Write (request)", id: Command.att-write-req},
                {title: "Exchange MTU", id: Command.att-mtu},
            ],
        },
        {
            title: "GATT Server",
            items: [
                {title: "Notify", id: Command.att-notify},
                {title: "Read own", id: Command.att-read-own},
                {title: "Write own", id: Command.att-write-own},
            ],
        }
    ];

    MenuBar {
        for menu in menus : Menu {
            title: menu.title;
            for item in menu.items: MenuItem {
                title: item.title;
                activated => { button(item.id); }
            }
        }
    }

    VerticalLayout {
        HorizontalLayout {
            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;
                max-width: 100px;
                Button {
                    text: "Start scan";
                    clicked => {root.button(Command.start-scan);}
                }

                Button {
                    text: "Stop scan";
                    clicked => {root.button(Command.stop-scan);}
                }

                Button {
                    text: "Connect";
                    clicked => {root.button(Command.connect);}
                }

                Button {
                    text: "Bond";
                    clicked => {root.button(Command.bond);}
                }

                Button {
                    text: "Disconnect";
                    clicked => {root.button(Command.disconnect);}
                }
            }

            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                property<bool> scan-focused: true;

                VerticalBox {
                    padding: 0px;
                    HorizontalBox {
                        padding: 0px;
                        Button {
                            text: "Scan results";
                            clicked => { scan-focused = true; }
                        }

                        for device[i] in root.all-devices : Button {
                            text: device.address;
                            clicked => { root.active-tab = i+1; scan-focused = false; }
                        }
                    }

                    Rectangle {
                        min-height: 300px;
                        min-width: 600px;

                        VerticalBox {
                            visible: scan-focused;

                            LineEdit {
                                placeholder-text: "Device filter (name/address)";
                                edited(text) => {
                                    root.scan-filter.text = text;
                                    root.filter-scan-results(scan-filter);
                                }
                            }

                            Rectangle {
                                results := ScanResults {
                                    sort-scan-results-cb(idx, asc) => {
                                        root.scan-filter.column = idx;
                                        root.scan-filter.ascending = asc;
                                        root.filter-scan-results(scan-filter);
                                    }
                                }
                            }
                        }

                        for device[i] in root.all-devices : GattView {
                            data: device;
                            visible: (root.active-tab == i+1) && !scan-focused;
                        }
                    }
                }

                log-viewer:= TextEdit {
                    min-height: 100px;
                    font-size: 12px;
                    read-only: true;
                    wrap: word-wrap;
                    text: root.log-text;
                    function go-to-bottom() {
                        self.viewport-y = min(0px, - self.viewport-height + self.visible-height);
                    }
                }
            }
        }
    }
}
