import {
    Button,
    StandardTableView,
    TextEdit,
    TabWidget,
} from "std-widgets.slint";

component ScanResults inherits Rectangle {
    // StandardTableView rows are a model of models (a list of rows, where each row is a list of items)
    in-out property <[[StandardListViewItem]]> device_rows: [];
    in-out property <int> current-row: tv.current-row;

    min-width: 500px;
    min-height: 200px;
    VerticalLayout {
        tv := StandardTableView {
            columns: [
                { title: "Address", min-width: 50px },
                { title: "RSSI" },
                { title: "Name" },
                { title: "Data" },
            ];
            rows: root.device_rows;
        }
    }
}

export enum Command { start-scan, stop-scan, connect, bond, disconnect }

export component AppWindow inherits Window {
    // Define the callback here so Rust can "see" it
    callback button(Command);

    in-out property <[[StandardListViewItem]]> scan_results <=> results.device_rows;
    in-out property <int> selected_device <=> results.current-row;

    VerticalLayout {
        HorizontalLayout {
            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;
                max-width: 100px;
                Button {
                    text: "Start scan";
                    clicked => {root.button(Command.start-scan);}
                }

                Button {
                    text: "Stop scan";
                    clicked => {root.button(Command.stop-scan);}
                }

                Button {
                    text: "Connect";
                    clicked => {root.button(Command.connect);}
                }

                Button {
                    text: "Bond";
                    clicked => {root.button(Command.bond);}
                }

                Button {
                    text: "Disconnect";
                    clicked => {root.button(Command.disconnect);}
                }
            }

            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                TabWidget {
                    Tab {
                        title: "Scan results";
                        results := ScanResults { }
                    }

                    Tab {
                        title: "Device A";
                        Rectangle {
                            min-height: 200px;
                            background: orange;
                        }
                    }
                }

                TextEdit {
                    min-height: 100px;
                    font-size: 12px;
                    text: "this is a log line\n and another";
                }
            }
        }
    }
}
