import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

struct DashboardData {
    title: string,
    counter: int,
}

component DashboardView inherits Rectangle {
    in property <DashboardData> data;
    background: #333;
    border-width: 1px;
    border-color: gray;

    Text {
        text: "View: " + root.data.title + " | Value: " + root.data.counter;
        color: white;
    }
}

export component AppWindow inherits Window {
    // Rust will provide this list
    in property <[DashboardData]> all_dashboards: [{title: "one", counter: 1}, {title: "two", counter: 2}];
    in-out property <int> active_idx: 0;

    VerticalBox {
        // Tab Headers
        HorizontalBox {
            for dash[i] in root.all_dashboards : Button {
                text: dash.title;
                clicked => { root.active_idx = i; }
            }
        }

        // The View Area
        Rectangle {
            height: 200px;
            width: 200px;

            // This creates an instance for EVERY item in the Rust Vec
            for dash[i] in root.all_dashboards : DashboardView {
                data: dash;
                // Only show the one we selected
                visible: root.active_idx == i;
            }
        }
    }
}
